In [11]:
import numpy as np
from numpy import linalg

In [21]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 
#(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
N = 10
arr = np.arange(0,N)
reversed_arr = arr[::-1]
print(arr)
print(reversed_arr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [39]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. 
#Посчитайте сумму ее значений на диагонали.
m_diag_np = np.diag(reversed_arr)
Sum = sum(reversed_arr)
print(m_diag_np)
print (f'Сумма значений по диогонали равна {Sum}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений по диогонали равна 45


In [13]:
#Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array ([4,12,-3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

Задание 4. На сайт заходит очередной посетитель,о покупках которого известно следующее:

In [45]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [41]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

In [ ]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [76]:
users_dict = dict()
cos_ = []
for i, el in enumerate (users_stats):
    a = np.arccos( cosine( el, next_user_stats ) ) * 360 / 2 / np.pi
    users_dict[i+1] = [a]
    cos_.append(a)
print(users_dict)
minimum = min(cos_)
for key, value in users_dict.items():
    if value == minimum:
        print(f'Самый схожий пользователь с next_user_stats пользователь номер {key}')

{1: [78.46304096718453], 2: [32.311533237423866], 3: [66.42182152179818], 4: [37.761243907035045], 5: [66.42182152179818], 6: [90.0], 7: [90.0], 8: [18.434948822922017], 9: [90.0], 10: [90.0]}
Самый схожий пользователь с next_user_stats пользователь номер 8
